/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Joel' at '2/17/17 7:28 PM' with Gradle 2.14.1
 *
 * @author Joel, @date 2/17/17 7:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
